[build-system]
requires = ["setuptools>=80.0", "setuptools_scm>=9"]
build-backend = "setuptools.build_meta"

[project]
name = "lightworks"
description = "Open-source Python SDK for photonic quantum computation."
license = "Apache-2.0"
requires-python = ">=3.10"
dynamic = ["version", "readme"]
authors = [
  { name = "Aegiq Ltd." },
]
dependencies = [
  "thewalrus==0.20.0",
  "matplotlib>=3.7.1",
  "pandas>=2.0.1",
  "numpy>=1.24.3",
  "multimethod>=1.11.2",
  "drawsvg>=2.3.0",
  "CairoSVG>=2.8.0",
  "sympy>=1.12.0",
  "pyarrow",
  "ipython",
]
classifiers = [
  "Natural Language :: English",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/Aegiq/lightworks"
Source = "https://github.com/Aegiq/lightworks"
Documentation = "https://aegiq.github.io/lightworks/"

[project.optional-dependencies]
remote = ["lightworks-remote>=1.2.3"]
qiskit = ["qiskit[visualization]>=1.1.0"]
all = ["lightworks[qiskit,remote]"]

[dependency-groups]
dev = [
    "sphinx",
    "furo",
    "nbsphinx",
    "sphinx-copybutton",
    "sphinxcontrib-bibtex",
    "pytest",
    "pytest-rerunfailures",
    "pytest-cov",
    "ruff>=0.8.1",
    "mypy>=1.13.0",
    "ipykernel",
]

[tool.setuptools.dynamic]
readme = { file = "README.md", content-type = "text/markdown" }

[tool.setuptools.packages.find]
exclude = ["tests*"]

[tool.setuptools.package-data]
lightworks = ["py.typed"]

[tool.setuptools_scm]
version_file = "lightworks/__version.py"

## pytest config
[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra"
testpaths = [
    "tests",
]

## pytest coverage config
[tool.coverage.run]
omit = [
    "tests/*",
    "docs/*",
    "lightworks/qubit/converter/__init__.py"
]

[tool.coverage.report]
exclude_also = [
    "if TYPE_CHECKING:",
    "def __repr__"
]

## mypy config
[tool.mypy]
files = "lightworks"
disable_error_code = 'import-untyped, import-not-found'
strict_equality = true
extra_checks = true
check_untyped_defs = true

disallow_any_generics = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_untyped_decorators = true
disallow_untyped_defs = true

[[tool.mypy.overrides]]
module = "thewalrus.*, drawsvg.*, scipy.*, scipy.*.stats.*"
ignore_missing_imports = true

## ruff config
[tool.ruff]
exclude = [
    "venv",
    "setup.py",
    "lightworks/__version.py"
]
line-length = 80
indent-width = 4
target-version = "py311"

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint]
preview = true
select = ["ALL"]
fixable = ["ALL"]
ignore = [
    "ANN401",
    "C901",
    "COM812",
    "D100",
    "D104",
    "D105",
    "D107",
    "D200",
    "D205",
    "D212",
    "D412",
    "D415",
    "D421",
    "DOC201",
    "DOC402",
    "DOC501",
    "EM101",
    "FBT",
    "PLR09",
    "PT011",
    "PLR1702",
    "PLR2004",
    "PLR6301",
    "RUF067",
    "S311",
    "SLF001",
    "TD",
    "TRY003",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["PERF", "ANN", "S101", "PLC2701", "SLF001", "DOC201"]
"docs/*" = ["ANN", "B905", "CPY001", "D", "E731", "T201"]
"docs/source/conf.py" = ["INP001"]
"docs/source/tutorials/qubit.ipynb" = ["E402"]
".github/workflows/*" = ["CPY001", "INP001", "PTH123"]

[tool.ruff.lint.flake8-pytest-style]
parametrize-names-type = "tuple"
parametrize-values-row-type = "tuple"

[tool.ruff.lint.flake8-builtins]
builtins-ignorelist = ["input"]