# Workflow for uploading to pypi
name: Upload to PyPi

# Run on version release
on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest
    environment: pypi
    permissions: # Needed for trusted publishing
        id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        python-version: 3.13
        
    - name: Build package
      run: uv build
      
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1.12


  update_citation:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
        ref: main
    
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
        uv venv
        uv pip install .

    - name: Update citation file
      run: uv run .github/workflows/update_citation.py

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update CITATION.cff file
        