# Workflow for uploading to pypi
name: Upload to PyPi

# Run on version release
on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest
    environment: pypi
    permissions: # Needed for trusted publishing
        id-token: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        
    - name: Build package
      run: python -m build
      
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1.8


  update_citation:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install lightworks
      run: | 
          python -m pip install --upgrade pip
          pip install .

    - name: Update citation file
      run: |
          python .github/workflows/update_citation.py

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update CITATION.ff file
        