# Used to check docs can be built when pull requests are made
name: Test Build Docs

on:
  # Triggers the workflow on pull request events for main
  pull_request:
    branches:
      - main

  # Allows workflow to be manually run from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs: 

  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: 3.13
        
      - name: Install dependencies
        run: |
          uv venv
          uv pip install -r requirements.txt

      # Pandoc install required for sphinx docs
      - name: Install pandoc
        run: |
          wget https://github.com/jgm/pandoc/releases/download/3.6.3/pandoc-3.6.3-1-amd64.deb
          sudo dpkg -i pandoc-3.6.3-1-amd64.deb
        
      # Run sphinx build from docs folder
      - name: Build HTML
        run: | 
          source .venv/bin/activate
          cd docs/
          make html SPHINXOPTS="--fail-on-warning"
