# Used to build and deploy sphinx docs on submission to main
name: Deploy Docs

on:
  # Triggers the workflow on push events for main
  push:
    branches: [main]

  # Allows workflow to be manually run from the Actions tab
  workflow_dispatch:

# Define build job
jobs: 

  build: 
    # Choose to run on ubuntu
    runs-on: ubuntu-latest

    steps:
      # Checks-out repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Create Python 3.11 environment
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
           python-version: "3.11"
        
      # Install all dependencies from requirements file and ghp-import
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ghp-import

      # Pandoc install required for sphinx docs
      - name: Install pandoc
        run: |
          wget https://github.com/jgm/pandoc/releases/download/3.1.12.2/pandoc-3.1.12.2-1-amd64.deb
          sudo dpkg -i pandoc-3.1.12.2-1-amd64.deb
        
      # Run sphinx build from docs folder
      - name: Build HTML
        run: | 
          cd docs/
          make html
      
      # Use ghp-import on build folder to export docs
      - name: Run ghp-import
        run: | 
          ghp-import -n -p -f docs/build/html
