# Used to build and deploy sphinx docs on submission to main
name: Deploy Docs

on:
  # Triggers the workflow on push events for main
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 2 1 *'

  # Allows workflow to be manually run from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs: 

  deploy: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ vars.MAIN_PY_VER }}
        
      - name: Install dependencies
        run: |
          uv venv
          uv pip install -r requirements.txt
          uv pip install ghp-import --system

      # Pandoc install required for sphinx docs
      - name: Install pandoc
        run: |
          wget https://github.com/jgm/pandoc/releases/download/3.6.3/pandoc-3.6.3-1-amd64.deb
          sudo dpkg -i pandoc-3.6.3-1-amd64.deb
        
      # Run sphinx build from docs folder
      - name: Build HTML
        run: |
          source .venv/bin/activate
          cd docs/
          make html SPHINXOPTS="--fail-on-warning"
      
      # Use ghp-import on build folder to export docs
      - name: Run ghp-import
        run: uv run ghp-import -n -p -f docs/build/html
