# Used to check docs can be built when pull requests are made
name: Build-sphinx-docs

on:
  # Triggers the workflow on pull request events for main
  pull_request:
    branches: [main, development]

  # Allows workflow to be manually run from the Actions tab
  workflow_dispatch:

# Define build job
jobs: 

  build: 
    # Choose to run on ubuntu
    runs-on: ubuntu-latest

    steps:
      # Checks-out repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Create Python 3.11 environment
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
           python-version: "3.11"
        
      # Install all dependencies from requirements file and ghp-import
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Pandoc install required for sphinx docs
      - name: Install pandoc
        run: |
          sudo apt update
          sudo apt install pandoc
        
      # Run sphinx build from docs folder
      - name: Build HTML
        run: | 
          cd docs/
          make html
