name: Test

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  schedule:
    - cron: '0 0 * * 1'

  # Allows workflow to be manually run from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  pytest:

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        os: [ubuntu-latest]
        include:
          - python-version: ${{ vars.MAIN_PY_VER }}
            os: windows-latest
          - python-version: ${{ vars.MAIN_PY_VER }}
            os: macos-latest

    runs-on: ${{ matrix.os }}
    
    # Runs for each version
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          uv venv
          uv pip install -r requirements.txt

      - name: Test with pytest
        if: ${{ ! (matrix.python-version == vars.MAIN_PY_VER && matrix.os == 'ubuntu-latest' && github.event_name == 'pull_request') }}
        run: uv run pytest
        
      - name: Test with pytest & coverage
        if: ${{ matrix.python-version == vars.MAIN_PY_VER && matrix.os == 'ubuntu-latest' && github.event_name == 'pull_request' }}
        run: uv run pytest --junitxml=report.xml --cov --cov-report=term-missing:skip-covered --cov-report xml:coverage.xml

      # Add comment to PR with coverage report
      - name: Pytest coverage comment
        if: ${{ matrix.python-version == vars.MAIN_PY_VER && matrix.os == 'ubuntu-latest' && github.event_name == 'pull_request' }} 
        uses: MishaKav/pytest-coverage-comment@main
        with:
          junitxml-path: ./report.xml
          pytest-xml-coverage-path: ./coverage.xml
          remove-link-from-badge: true
