name: Test

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  schedule:
    - cron: '0 8 1,15 * *'

  # Allows workflow to be manually run from the Actions tab
  workflow_dispatch:
        
jobs:
  pytest:

    runs-on: ubuntu-latest
    strategy:
        matrix:
            python-version: ["3.10", "3.11", "3.12", "3.13"]

    # Runs for each version
    steps:
      - uses: actions/checkout@v4

      # Configures the Python version
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
            python-version: ${{ matrix.python-version }}

      # Install all dependencies from requirements file 
      - name: Install dependencies
        run: | 
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      # Run with pytest
      - name: Test with pytest
        run: |
            pytest --junitxml=report.xml --cov --cov-report=term-missing:skip-covered --cov-report xml:coverage.xml

      # Add comment to PR with coverage report
      - name: Pytest coverage comment
        if: ${{ matrix.python-version == '3.11'  && github.event_name == 'pull_request' }} 
        uses: MishaKav/pytest-coverage-comment@main
        with:
          junitxml-path: ./report.xml
          pytest-xml-coverage-path: ./coverage.xml
          remove-link-from-badge: true
